---
- name: "Create user {{ _postgresql__user.value.username }}"
  postgresql_user:
    user: "{{ _postgresql__user.value.username }}"
    password: "{{ _postgresql__user.value.password }}"
    role_attr_flags: "LOGIN,INHERIT"
    groups: "{{ _postgresql__user.value.role }}"
  environment:
    PGOPTIONS: "-c password_encryption=scram-sha-256"
  become_user: postgres
